#!/bin/bash

# simple curl based serval-dna journal frontend
# Copyright: Lars Baumgaertner (c) 2017

#SERVICE="sensor"
#NAME="textlog4"

. $(dirname $(readlink -f $0))/libservalcurl.sh

if [ "$#" -lt 1 ]; then
    echo "USAGE: $0 <command> [parameters...]"
    echo " COMMANDS:"
    echo "  ls # list all rhizome files"
    echo "  list <service> <name> # bundle list filtered by service and name"
    echo "  show <bundle id> # show bundle content"
    echo "  append <service> <name> <entry> # append/create journal"
    exit
fi


# args: <service> <name> <journal_entry>
function journal_append {
    SIDA=$(get_first_identity)
    BID=$(get_bundle_id $1 $2 $SIDA)
    if [ -z "$BID" ] ; then    
        journal_new $SIDA $1 $2 "$3"
    else    
        journal_update $SIDA $BID "$3"
    fi

}

if [ "$1" = "list" ]; then
    get_bundle_list $2 $3
fi
if [ "$1" = "show" ]; then
    get_bundle_content $2    
fi
if [ "$1" = "append" ]; then    
    journal_append "$2" "$3" "$4"
fi
if [ "$1" = "ls" ]; then    
    get_rhizome_list
fi
exit
