#!/bin/bash

# simple curl based serval-dna content trigger similar to dtntrigger
# Copyright: Lars Baumgaertner (c) 2017

. $(dirname $(readlink -f $0))/libservalcurl.sh

if [ "$#" -lt 1 ]; then
    echo "USAGE: $0 <command> [service-filter] [filename-filter]"
    echo " "
    echo "  <command> # trigger this command service, name and BID as paramters"
    echo "  [service-filter] # filter for this service only"
    echo "  [filename-filter] # filter for this service only"    
    exit
fi

COMMAND=$1
SERVICEFILTER=".*"
FILEFILTER=".*"

if [ -n "$2" ]; then
    SERVICEFILTER=$2
fi
if [ -n "$3" ]; then
    FILEFILTER=$3
fi
echo "CMD: $COMMAND"
echo "SERVICE FILTER: $SERVICEFILTER"
echo "FILE FILTER: $FILEFILTER"

handler()
{
    echo "Cleaning up tmp files.."
    rm ${temp_file}
    exit        
}

temp_file=$(mktemp)
token=$(curl -H "Expect:" --silent --basic --user $RESTAUTH http://127.0.0.1:4110/restful/rhizome/bundlelist.json | jq --raw-output '.rows[0][0]')

echo $token > $temp_file
trap handler SIGINT

while true; do
    token=$(cat $temp_file)
    #echo Token: $token

    buf=""
    started=0
    curl -H "Expect:" --silent --no-buffer --basic --user $RESTAUTH http://127.0.0.1:4110/restful/rhizome/newsince/$token/bundlelist.json | while read -N 1 line ; do            
        buf="$buf$line"
        if [[ $buf =~ ^.*\"rows\"\:\[ ]]; then    
            started=1
            buf=""    
        elif [ "$started" == 1 ]; then        
            if [[ $buf =~ ^.*\] ]]; then
                if [ ${#buf} -ge 15 ]; then
                    entry=$(echo $buf | sed -e "s/^,//")    
                    token=$(echo $entry | jq --raw-output '.[0]')
                    echo $token > $temp_file
                    BID=$(echo $entry | jq --raw-output '.[3]')
                    SERVICE=$(echo $entry | jq --raw-output '.[2]')
                    NAME=$(echo $entry | jq --raw-output '.[13]')

                    if [[ "$SERVICE" =~ $SERVICEFILTER ]]; then                        
                        if [[ "$NAME" =~ $FILEFILTER ]]; then
                            echo "TRIGGER ($(date)): $SERVICE $NAME $BID"

                            if [ -n "$COMMAND" ]; then
                                echo "Executing $COMMAND"
                                $COMMAND "$SERVICE" "$NAME" $BID
                            fi
                        fi
                    fi           
                    buf=""
                fi
            fi
        fi    
    done
done

rm ${temp_file}
