#!/bin/bash

USER="pum"
PASS="pum123"


RESTAUTH="$USER:$PASS"
# args: none
function get_first_identity {
    curl -H "Expect:" --silent --dump-header http.header \
        --basic --user $RESTAUTH \
        "http://127.0.0.1:4110/restful/keyring/identities.json" \
        | grep -A 1 rows | tail -n1 | cut -d "\"" -f 2
}


export SERVALINSTANCE_PATH=$(pwd)
echo "Starting daemon"
servald start > /dev/null

echo "Setting interfaces to 'eth*'"
servald config set interfaces.0.match 'eth*' > /dev/null
echo "Setting RESTAUTH to $RESTAUTH"
servald config set api.restful.users.$USER.password $PASS > /dev/null

SID=$(get_first_identity)
if [ ${#SID} -lt 64 ]; then 
    echo "Creating new identity"
    servald keyring add
    
    echo "Restarting daemon"
    servald stop > /dev/null
    #servald status 
    sleep 1
    servald start > /dev/null
    #servald status
fi

if [ $# -gt 0 ]; then
    echo "Going interactive"
    bash
fi
